PhotoSchool/urls.py
from django.contrib import admin
from django.urls import path, include
from navigation import views as nav_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('custom_admin/', include('custom_admin.urls')),
    path('teacher_panel/', include('teacher_panel.urls')),
    path('admin/', admin.site.urls),
    # navigation
    path('', nav_views.home, name='home'),
    path('courses', nav_views.courses, name='list_courses'),
    path('me', nav_views.user_profile, name='user_profile'),
    path('c/<int:course_id>', nav_views.details_course, name='nav_details_course'),
    path('trenapp', nav_views.trenapp, name='trenapp'),
    path('authors', nav_views.authors, name='authors'),


    path('trenapp/camera', nav_views.camera, name='camera'),
    path('get_certificate/<int:complete_course_id>', nav_views.certificate, name='certificate'),


    path('s/', include('stud_process.urls')),

    path('auth/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher_panel/urls.py
from django.contrib.auth.decorators import user_passes_test
from django.urls import path
from . import views

app_name = 'teacher_panel'

urlpatterns = [
    # check task pages
    path('',
         user_passes_test(lambda u: u.is_staff)(views.general_page),
         name='general_page'),
    path('check_task',
         user_passes_test(lambda u: u.is_staff)(views.check_task_list_courses),
         name='check_task_list_courses'),
    path('check_task/<int:course_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_task_list_tasks),
         name='check_task_list_tasks'),
    path('check_task/<int:course_id>/<int:task_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_task_solution_list),
         name='check_task_solution_list'),
    path('check_task/<int:course_id>/<int:task_id>/<int:solution_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_task_solution_details),
         name='check_task_solution_details'),
    # Check users pages
    path('check_users',
         user_passes_test(lambda u: u.is_staff)(views.check_users_list_users),
         name='check_users_list_users'),
    path('check_users/<int:user_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_users_details),
         name='check_users_details'),
    path('check_users/<int:user_id>/<int:course_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_users_details_course),
         name='check_users_details_course'),
    path('check_users/<int:user_id>/<int:course_id>/<str:lesson_type>/<int:lesson_id>',
         user_passes_test(lambda u: u.is_staff)(views.check_users_details_lesson),
         name='check_users_details_lesson'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    #path('', views.confirm, name='confirm_code'),
]

content/models.py
from django.db import models
from itertools import chain
from operator import attrgetter
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import User


class Course(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    photo = models.ImageField(upload_to="course_photo", blank=True)
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False, blank=True, verbose_name='Отметить как черновик')
    tab_index = models.IntegerField(default=0)

    def get_lessons(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        lessons = []
        for module in modules_list:
            lessons = lessons + module.get_lessons()
        return lessons

    def get_count_lessons(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        counts = {'ts': 0, 'lc': 0, 'tk': 0}
        lessons = []

        for module in modules_list:
            lessons = lessons + module.get_lessons()

        for lesson in lessons:
            if lesson.content_type == 'lc' or lesson.content_type == 'vd':
                counts['lc'] += 1
            elif lesson.content_type == 'ts':
                counts['ts'] += 1
            elif lesson.content_type == 'tk':
                counts['tk'] += 1
        return counts

    def get_full_content(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        modules = []
        for module in modules_list:
            modules.append({'module_object': module, 'lessons': module.get_lessons()})
        return {'course': self, 'modules': modules}

    def get_course_tree(self, user):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        modules = []
        for module in modules_list:
            modules.append({'module_object': module, 'lessons': module.get_lessons_tree(user)})
        return {'course': self, 'modules': modules}


class Module(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False, verbose_name='Отметить как черновик')
    tab_index = models.IntegerField(default=0)

    def get_lessons(self):
        videos = VideoLecture.objects.filter(module_id=self, is_draft=False)
        tasks = Task.objects.filter(module_id=self,  is_draft=False)
        lectures = Lecture.objects.filter(module_id=self,  is_draft=False)
        tests = Test.objects.filter(module_id=self,  is_draft=False)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        return lessons

    def get_lessons_tree(self, user):
        videos = VideoLecture.objects.filter(module_id=self, is_draft=False)
        tasks = Task.objects.filter(module_id=self,  is_draft=False)
        lectures = Lecture.objects.filter(module_id=self,  is_draft=False)
        tests = Test.objects.filter(module_id=self,  is_draft=False)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        # for lesson in lessons:
        #     if CompletedLessons.objects.filter(user=user, lesson_type=lesson.content_type, lessons_id=lesson.id):
        #         lesson['passed'] = True
        #     else:
        #         lesson['passed'] = False

        return lessons

    def get_lessons_with_draft(self):
        videos = VideoLecture.objects.filter(module_id=self)
        tasks = Task.objects.filter(module_id=self)
        lectures = Lecture.objects.filter(module_id=self)
        tests = Test.objects.filter(module_id=self)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        return lessons


class Lesson(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    module_id = models.ForeignKey(Module, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    stop_lesson = models.BooleanField(default=False)
    tab_index = models.IntegerField(default=0)
    content_type = models.CharField(max_length=2, choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')])
    is_draft = models.BooleanField(default=False, verbose_name='Отметить как черновик')

    class Meta:
        abstract = True


# Lessons models
class Lecture(Lesson):
    text = models.TextField(verbose_name='Текст лекции')


class VideoLecture(Lesson):
    video = models.FileField(upload_to="videos", verbose_name='Видео')


# Tests models
class Test(Lesson):
    time = models.IntegerField(default=15, validators=[MinValueValidator(0), MaxValueValidator(60)], verbose_name='Время на выполнение (минуты)')
    min_ball = models.IntegerField(default=60, validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name='Минимальный балл')

    def get_full(self):
        full_test = {'test': self, 'questions': []}
        questions = Question.objects.filter(test_id=self)
        for question in questions:
            full_test['questions'].append({'question': question, 'answers': Answer.objects.filter(question_id=question)})

        return full_test


class Question(models.Model):
    test_id = models.ForeignKey(Test, on_delete=models.CASCADE)
    description = models.TextField(max_length=100, blank=True, verbose_name='Описание')
    text = models.TextField()


class Answer(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    is_true = models.BooleanField(default=False)


# Tasks models
class Task(Lesson):
    text = models.TextField()
    response_is_file = models.BooleanField(default=False)

stud_process/models.py
from django.db import models
from content.models import Course, Module, Task, Test
from users.models import User


class CompletedLessons(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    lesson_type = models.CharField(max_length=2, choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')], verbose_name='Тип урока')
    lesson_id = models.IntegerField(verbose_name='ID Урока')
    date = models.DateField(auto_now_add=True, verbose_name='Дата выполнения')


class CompletedCourses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    date = models.DateField(auto_now_add=True, verbose_name='Дата')


class InStudying(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    date_started = models.DateField(auto_now_add=True, verbose_name='Дата начала')


class TaskSolutions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, verbose_name='Задание')
    text = models.TextField(max_length=1000, verbose_name='Ответ')
    file = models.FileField(blank=True, verbose_name='Файл')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    is_rejected = models.BooleanField(default=False, verbose_name='Отметить отклоненным')
    is_true = models.BooleanField(default=False, verbose_name='Отметить завершенным')


class TestResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name='Тест')
    ball = models.FloatField(verbose_name='Балл')

teacher_panel/models.py
from django.db import models

# Create your models here.

teacher_panel/views.py
from django.shortcuts import render, redirect, reverse
from stud_process.models import TaskSolutions, CompletedLessons, InStudying, CompletedCourses, TestResult
from content.models import Course, Task, Lecture, VideoLecture, Test
from users.models import User


def general_page(request):
    return render(request, 'teacher_panel/general_page.html')


def check_task_list_courses(request):
    courses = []
    courses_ids = []
    message = None
    task_solutions = TaskSolutions.objects.filter(is_true=False)
    for ts in task_solutions:
        course_id = ts.task.module_id.course_id.id
        if not (course_id in courses_ids):
            courses_ids.append(course_id)
            courses.append(ts.task.module_id.course_id)
    if not courses:
        message = 'Не проверенных заданий нет'
    return render(request, 'teacher_panel/ct_list_courses.html', {'courses': courses, 'message': message})


def check_task_list_tasks(request, course_id):

    tasks = []
    tasks_ids = []
    course = Course.objects.get(pk=course_id)
    message = None
    task_solutions = TaskSolutions.objects.filter(is_true=False)
    for ts in task_solutions:
        task_id = ts.task.id
        if not (task_id in tasks_ids):
            tasks_ids.append(course_id)
            tasks.append(ts.task)
    if not tasks:
        message = 'Не проверенных заданий курсе нет'
    return render(request, 'teacher_panel/ct_list_tasks.html', {'course': course, 'tasks': tasks, 'message': message})


def check_task_solution_list(request, course_id, task_id):
    message = None
    course = Course.objects.get(pk=course_id)
    task = Task.objects.get(pk=task_id)
    task_solutions = TaskSolutions.objects.filter(is_true=False)
    if not task_solutions:
        message = 'Не проверенных заданий у данного урока нет'
    print(task_solutions)
    return render(request, 'teacher_panel/ct_list_solutions.html', {'course': course, 'task': task, 'solutions': task_solutions, 'message': message})


def check_task_solution_details(request, course_id, task_id, solution_id):
    task_solution = TaskSolutions.objects.get(pk=solution_id)
    course = Course.objects.get(pk=course_id)
    task = Task.objects.get(pk=task_id)

    if request.method == "GET":
        return render(request, 'teacher_panel/ct_solution_details.html',
                  {'course': course, 'task': task, 'solution': task_solution})
    else:
        if request.POST.get("accept"):
            task_solution.comment = request.POST.get("comment")
            task_solution.is_true = True
            task_solution.save()
            cl = CompletedLessons(user=task_solution.user, lesson_type='tk', lesson_id=task.id)
            cl.save()
            return redirect(reverse('teacher_panel:check_task_solution_list', args=[course_id, task_id]))
        elif request.POST.get("reject"):
            task_solution.comment = request.POST.get("comment")
            task_solution.is_rejected = True
            task_solution.save()
            return redirect(reverse('teacher_panel:check_task_solution_list', args=[course_id, task_id]))


def check_users_list_users(request):
    users = User.objects.filter()
    message = None
    return render(request, 'teacher_panel/cu_list_users.html',
                  {'users': users, 'message': message})


def check_users_details(request, user_id):
    user = User.objects.get(pk=user_id)
    message = None
    courses = InStudying.objects.filter(user=user)
    count_courses_pass = len(CompletedCourses.objects.filter(user=user))
    print(courses)
    if not courses:
        message = 'Пользователь еще не проходил курсы'
    return render(request, 'teacher_panel/cu_user_details.html',
                  {'user': user, 'courses': courses, 'message': message, 'count_courses_pass': count_courses_pass})


def check_users_details_course(request, user_id, course_id):
    user = User.objects.get(pk=user_id)
    course = Course.objects.get(pk=course_id)
    lessons = course.get_lessons()
    lessons_with_status = []

    for lesson in lessons:
        is_pass = CompletedLessons.objects.filter(user=user, lesson_type=lesson.content_type, lesson_id=lesson.id)
        lessons_with_status.append({'lesson': lesson, 'is_pass': bool(is_pass)})

    return render(request, 'teacher_panel/cu_course_details.html',
                  {'user': user, 'course': course, 'lessons': lessons_with_status})


content_types = {'lc': Lecture, 'ts': Test, 'tk': Task, 'vd': VideoLecture}


def check_users_details_lesson(request, user_id, course_id, lesson_type, lesson_id):
    lesson = content_types[lesson_type].objects.get(pk=lesson_id)
    user = User.objects.get(pk=user_id)
    course = Course.objects.get(pk=course_id)
    complete_lesson = CompletedLessons.objects.filter(user=user, lesson_type=lesson_type, lesson_id=lesson_id)

    if complete_lesson:
        complete_lesson = complete_lesson[0]
    else:
        complete_lesson = None
    task_solution = None
    test_result = None

    if lesson_type == 'ts':
        test_result = TestResult.objects.filter(user=user, test=lesson)

        if test_result:
            test_result = test_result[0]
        else:
            test_result = None

    elif lesson_type == 'tk':
        task_solution = TaskSolutions.objects.filter(user=user, task=lesson)

        if task_solution:
            task_solution = task_solution[0]
        else:
            task_solution = None

    return render(request, 'teacher_panel/cu_lesson_details.html',
                  {'user': user, 'course': course, 'lesson': lesson, 'complete_lesson': complete_lesson, 'task_solution': task_solution, 'test_result': test_result})

teacher_panel/templates/teacher_panel/base_teacher_panel.html
<head>
    {% load static %}
    {% block head %}{% endblock %}
    <style>
        a {
            text-decoration: none;
        }
    </style>
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
</head>

<body>
<header class="p-3 bg-dark text-white">

    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start position-relative">
          <div>
              <h1>Панель преподавателя <a href="{% url 'home' %}" class="btn btn-outline-warning">Главная</a></h1>
          </div>

        {% if user.is_authenticated %}

          <div class="text-end d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start form position-absolute top-50 end-0 translate-middle-y">
            <form action="{% url 'users:logoutuser' %}" method="POST" style="margin: 0;">
                <a href="{% url 'user_profile' %}" class="link px-2 text-white">Вы вошли как: {{ user.email }}</a>
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">Выйти</button>
            </form>
          </div>

        {% else %}

            <div class="text-end">
                <a href="{% url 'users:loginuser' %}"> <button type="button" class="btn btn-outline-light me-2">Войти</button> </a>
                <a href="{% url 'users:signupuser' %}" class="btn btn-warning"> Зарегистрироваться</a>
            </div>

        {% endif %}

      </div>
    </div>
  </header>

<div class="container p-3">{% block content %}{% endblock %}</div>

<script src="/static/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>

teacher_panel/templates/teacher_panel/ct_list_courses.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

{% if message %}

<div class="alert alert-primary" role="alert">
    {{ message }}
</div>

{% endif %}

{% for course in courses %}

    <a href="{% url 'teacher_panel:check_task_list_tasks' course.id %}" class="text-decoration-none text-reset"><h2>{{ course.name }}</h2></a>

{% endfor %}

    <a href="{% url 'teacher_panel:general_page' %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/ct_list_solutions.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}
{% if message %}

<div class="alert alert-primary" role="alert">
    {{ message }}
</div>

{% endif %}

{% for solution in solutions %}
    <a href="{% url 'teacher_panel:check_task_solution_details' course.id  task.id solution.id %}" class="text-decoration-none text-reset"><h2>{{ solution.task.name }} - {{ solution.user.email }}</h2></a>
{% endfor %}

    <a href="{% url 'teacher_panel:check_task_list_tasks' course.id %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/ct_list_tasks.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

{% if message %}

<div class="alert alert-primary" role="alert">
    {{ message }}
</div>

{% endif %}

{% for task in tasks %}
    <a href="{% url 'teacher_panel:check_task_solution_list' course.id  task.id%}" class="text-decoration-none text-reset"><h2>{{ task.name }}</h2></a>
{% endfor %}

<a href="{% url 'teacher_panel:check_task_list_courses' %}"><button class="btn btn-outline-secondary">Назад</button></a>


{% endblock %}

teacher_panel/templates/teacher_panel/ct_solution_details.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}
    <p>
        <label for="id_owner">Выполнил:</label>
        <text  id="id_owner">
        {{ solution.user.last_name }} {{ solution.user.first_name }} {{ solution.user.patronymic }}
        </text>
    </p>
    <p>
        <label for="id_text">Текст ответа:</label>
        <text  id="id_text">
        {{ solution.text }}
        </text>
    </p>
    {% if solution.file %}
    <p>
        <label for="id_file">Прикреаленный файл:</label>
        <a href="/media/{{ solution.file }}" id="id_file" download>
            Скачать
        </a>
    </p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
    <p>
        <label for="id_comment">Комментарий:</label>
        <p><textarea name="comment" cols="40" rows="10" maxlength="1000" id="id_comment">{{ solution.comment }}</textarea></p>
    </p>
            <input name="accept" type="submit" class="btn btn-success" value="Принять">
            <input name="reject" type="submit" class="btn btn-danger" value="Отклонить">
            <button class="btn btn-outline-secondary">Отмена</button>

    </form>



{% endblock %}

teacher_panel/templates/teacher_panel/cu_course_details.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

    <p>
        <h4>
        <label for="id_owner">Студент:</label>
        <label  id="id_owner">
            {{ user.last_name }} {{ user.first_name }} {{ user.patronymic }}
        </label>
    </h4>
    </p>
    <p>
        <h4>
        <label for="course">Курс:</label>
        <label  id="course">
            {{ course.name }}
        </label>
    </h4>
    </p>


 <h5>Уроки:</h5>


{% for lesson in lessons %}

    <a href="{% url 'teacher_panel:check_users_details_lesson' user.id course.id lesson.lesson.content_type lesson.lesson.id %}" class="{% if lesson.is_pass %}link-success{% else %}link-secondary{% endif %} text-decoration-none ">
        <h4>
            {{ lesson.lesson.name }}
        </h4>
    </a>

{% endfor %}

    <a href="{% url 'teacher_panel:check_users_details' user.id %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/cu_lesson_details.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

    <p>
        <h4>
        <label for="id_owner">

                Студент:

        </label>
        <label  id="id_owner">

            {{ user.last_name }} {{ user.first_name }} {{ user.patronymic }}

        </label>
        </h4>
    </p>
    <p>
        <h4>
        <label for="course">Курс:</label>
        <label  id="course">
            {{ course.name }}
        </label>
        </h4>
    </p>
    <p>
        <h4>
        <label for="lesson">Урок:</label>
        <label  id="lesson">
            {{ lesson.name }}
        </label>
        </h4>
    </p>
    <p>
        <h4>
        <label for="is_passed">Пройден:</label>
        <label  id="is_passed">
            {% if complete_lesson %}
                {{ complete_lesson.date }}
            {% else %}
                нет
            {% endif %}
        </label>
        </h4>
    </p>

    {% if task_solution %}

    <p>
        <h4>
        <label for="state">Статус ответа:</label>
        <label  id="state">
            {% if task_solution.is_true %}
                Принят
            {% elif task_solution.is_rejected %}
                Откланен
            {% else %}
                не определен
            {% endif %}
        </label>
    </h4>
    </p>

    {% endif %}

    {% if test_result %}

    <p>
        <h4>
        <label for="result">Лучший результат:</label>
        <label  id="result">
            {{ test_result.ball }} %
        </label>
    </h4>
    </p>

    {% endif %}

    <a href="{% url 'teacher_panel:check_users_details_course' user.id course.id %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/cu_list_users.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}
{% if message %}

<div class="alert alert-primary" role="alert">
    {{ message }}
</div>

{% endif %}

{% for user in users %}
    <a href="{% url 'teacher_panel:check_users_details' user.id %}" class="text-decoration-none text-reset">
        <h2>
            {{ user.last_name }} {{ user.first_name }} {{ user.patronymic }}
        </h2>
    </a>
{% endfor %}

    <a href="{% url 'teacher_panel:general_page' %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/cu_user_details.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

    <p>
        <h4>
        <label for="id_owner">Фио:</label>
        <label  id="id_owner">
            {{ user.last_name }} {{ user.first_name }} {{ user.patronymic }}
        </label>
    </h4>
    </p>
    <p>
        <h4>
        <label for="email">Эл. почта:</label>
        <label  id="email">
            {{ user.email }}
        </label>
    </h4>
    </p>
    <p>
        <h4>
        <label for="count_courses_pass">Курсов пройдено:</label>
        <label  id="count_courses_pass">
            {{ count_courses_pass }}
        </label>
        </h4>
    </p>


 <h5>Курсы:</h5>
{% if message %}

<div class="alert alert-primary" role="alert">
    {{ message }}
</div>

{% endif %}

{% for course in courses %}

    <a href="{% url 'teacher_panel:check_users_details_course' user.id course.course.id %}" class="text-decoration-none text-reset">
        <h4>
            {{ course.course.name }}
        </h4>
    </a>

{% endfor %}

    <a href="{% url 'teacher_panel:check_users_list_users' %}"><button class="btn btn-outline-secondary">Назад</button></a>

{% endblock %}

teacher_panel/templates/teacher_panel/general_page.html
{% extends 'teacher_panel/base_teacher_panel.html' %}

{% block content %}

    <a href="{% url 'teacher_panel:check_task_list_courses' %}" class="text-decoration-none text-reset"><h2>Проверка заданий</h2></a>
    <a href="{% url 'teacher_panel:check_users_list_users' %}" class="text-decoration-none text-reset"><h2>Студенты</h2></a>

{% endblock %}