PhotoSchool/urls.py
from django.contrib import admin
from django.urls import path, include
from navigation import views as nav_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('custom_admin/', include('custom_admin.urls')),
    path('teacher_panel/', include('teacher_panel.urls')),
    path('admin/', admin.site.urls),
    # navigation
    path('', nav_views.home, name='home'),
    path('courses', nav_views.courses, name='list_courses'),
    path('me', nav_views.user_profile, name='user_profile'),
    path('c/<int:course_id>', nav_views.details_course, name='nav_details_course'),
    path('trenapp', nav_views.trenapp, name='trenapp'),
    path('authors', nav_views.authors, name='authors'),


    path('trenapp/camera', nav_views.camera, name='camera'),
    path('get_certificate/<int:complete_course_id>', nav_views.certificate, name='certificate'),


    path('s/', include('stud_process.urls')),

    path('auth/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_admin/urls.py
from django.contrib.auth.decorators import user_passes_test
from django.urls import path
from . import views

app_name = 'custom_admin'

urlpatterns = [
    # general admin page
    path('',
         user_passes_test(lambda u: u.is_staff)(views.general_page),
         name='general_page'),
    # page with all courses
    path('courses/',
         user_passes_test(lambda u: u.is_staff)(views.all_courses),
         name='all_courses'),
    # page with one course (edit)
    path('course/<int:course_id>',
         user_passes_test(lambda u: u.is_staff)(views.details_course),
         name='details_course'),
    # added course page
    path('courses/add_course',
         user_passes_test(lambda u: u.is_staff)(views.add_course),
         name='add_course'),
    # page with one module (edit)
    path('course/<int:course_id>/module/<int:module_id>',
         user_passes_test(lambda u: u.is_staff)(views.details_module),
         name='details_module'),
    # added module page
    path('course/<int:course_id>/module/add_module',
         user_passes_test(lambda u: u.is_staff)(views.add_module),
         name='add_module'),
    # page with one lesson (edit)
    path('course/<int:course_id>/module/<int:module_id>/lesson/<str:lesson_type>/<int:lesson_id>',
         user_passes_test(lambda u: u.is_staff)(views.details_lesson),
         name='details_lesson'),
    # added lesson pages
    path('course/<int:course_id>/module/<int:module_id>/add_lesson/<str:lesson_type>',
         user_passes_test(lambda u: u.is_staff)(views.add_lesson),
         name='add_lesson'),

    path('users/',
         user_passes_test(lambda u: u.is_staff)(views.users),
         name='users'),

    path('users/<int:user_id>/',
         user_passes_test(lambda u: u.is_staff)(views.user_page),
         name='user_page'),


]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    #path('', views.confirm, name='confirm_code'),
]

content/models.py
from django.db import models
from itertools import chain
from operator import attrgetter
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import User


class Course(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    photo = models.ImageField(upload_to="course_photo", blank=True)
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False, blank=True, verbose_name='Отметить как черновик')
    tab_index = models.IntegerField(default=0)

    def get_lessons(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        lessons = []
        for module in modules_list:
            lessons = lessons + module.get_lessons()
        return lessons

    def get_count_lessons(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        counts = {'ts': 0, 'lc': 0, 'tk': 0}
        lessons = []

        for module in modules_list:
            lessons = lessons + module.get_lessons()

        for lesson in lessons:
            if lesson.content_type == 'lc' or lesson.content_type == 'vd':
                counts['lc'] += 1
            elif lesson.content_type == 'ts':
                counts['ts'] += 1
            elif lesson.content_type == 'tk':
                counts['tk'] += 1
        return counts

    def get_full_content(self):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        modules = []
        for module in modules_list:
            modules.append({'module_object': module, 'lessons': module.get_lessons()})
        return {'course': self, 'modules': modules}

    def get_course_tree(self, user):
        modules_list = Module.objects.filter(course_id=self, is_draft=False)
        modules = []
        for module in modules_list:
            modules.append({'module_object': module, 'lessons': module.get_lessons_tree(user)})
        return {'course': self, 'modules': modules}


class Module(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False, verbose_name='Отметить как черновик')
    tab_index = models.IntegerField(default=0)

    def get_lessons(self):
        videos = VideoLecture.objects.filter(module_id=self, is_draft=False)
        tasks = Task.objects.filter(module_id=self,  is_draft=False)
        lectures = Lecture.objects.filter(module_id=self,  is_draft=False)
        tests = Test.objects.filter(module_id=self,  is_draft=False)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        return lessons

    def get_lessons_tree(self, user):
        videos = VideoLecture.objects.filter(module_id=self, is_draft=False)
        tasks = Task.objects.filter(module_id=self,  is_draft=False)
        lectures = Lecture.objects.filter(module_id=self,  is_draft=False)
        tests = Test.objects.filter(module_id=self,  is_draft=False)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        # for lesson in lessons:
        #     if CompletedLessons.objects.filter(user=user, lesson_type=lesson.content_type, lessons_id=lesson.id):
        #         lesson['passed'] = True
        #     else:
        #         lesson['passed'] = False

        return lessons

    def get_lessons_with_draft(self):
        videos = VideoLecture.objects.filter(module_id=self)
        tasks = Task.objects.filter(module_id=self)
        lectures = Lecture.objects.filter(module_id=self)
        tests = Test.objects.filter(module_id=self)
        lessons = sorted(chain(videos, tasks, lectures, tests), key=attrgetter('tab_index'))
        return lessons


class Lesson(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    module_id = models.ForeignKey(Module, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    stop_lesson = models.BooleanField(default=False)
    tab_index = models.IntegerField(default=0)
    content_type = models.CharField(max_length=2, choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')])
    is_draft = models.BooleanField(default=False, verbose_name='Отметить как черновик')

    class Meta:
        abstract = True


# Lessons models
class Lecture(Lesson):
    text = models.TextField(verbose_name='Текст лекции')


class VideoLecture(Lesson):
    video = models.FileField(upload_to="videos", verbose_name='Видео')


# Tests models
class Test(Lesson):
    time = models.IntegerField(default=15, validators=[MinValueValidator(0), MaxValueValidator(60)], verbose_name='Время на выполнение (минуты)')
    min_ball = models.IntegerField(default=60, validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name='Минимальный балл')

    def get_full(self):
        full_test = {'test': self, 'questions': []}
        questions = Question.objects.filter(test_id=self)
        for question in questions:
            full_test['questions'].append({'question': question, 'answers': Answer.objects.filter(question_id=question)})

        return full_test


class Question(models.Model):
    test_id = models.ForeignKey(Test, on_delete=models.CASCADE)
    description = models.TextField(max_length=100, blank=True, verbose_name='Описание')
    text = models.TextField()


class Answer(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    is_true = models.BooleanField(default=False)


# Tasks models
class Task(Lesson):
    text = models.TextField()
    response_is_file = models.BooleanField(default=False)

custom_admin/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from .user_manager import NoUsernameUserManager


class User(AbstractUser):
    username = models.CharField(max_length=150, verbose_name='Логин')
    email = models.EmailField(unique=True, blank=True, verbose_name='Электронный адрес')
    patronymic = models.CharField("Отчество", max_length=150)
    first_name = models.CharField("Имя", max_length=150)
    last_name = models.CharField("Фамилия", max_length=150)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    objects = NoUsernameUserManager()

    def __str__(self):
        return self.email



# Create your models here.

custom_admin/forms.py
from django.forms import ModelForm
from content.models import Course, Module, VideoLecture, Lecture, Task, Test
from django_summernote.widgets import SummernoteWidget
from django import forms
from users.models import User


class FormCourse(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ))
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False)
    photo = forms.ImageField(required=False)
    is_draft = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False)

    class Meta:
        model = Course
        fields = ['name', 'description', 'photo', 'is_draft']


class FormModule(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ))
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False)
    is_draft = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False)

    class Meta:
        model = Module
        fields = ['name', 'description', 'is_draft']


class FormVideoLecture(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), label='Название лекции:')
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False,
                                  label="Описание:")
    is_draft = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False,
                                  label="Черновик:")
    video = forms.FileField(required=False, label="")
    class Meta:
        model = VideoLecture
        fields = ['name', 'description', 'video', 'is_draft']


class FormLecture(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), label='Название лекции:')
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False, label="Описание:")
    is_draft = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False, label="Черновик:")
    text = forms.CharField(widget=SummernoteWidget(attrs={"class": "form-control", "style": "width: 98%;"}, ), required=False, label="")
    class Meta:
        model = Lecture
        fields = ['name', 'description', 'text', 'is_draft']

        widgets = {
            'text': SummernoteWidget(),
        }


class FormTest(ModelForm):
    class Meta:
        model = Test
        fields = ['name', 'description', 'time', 'stop_lesson', 'is_draft', 'min_ball']


class FormTask(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), label='Название лекции:')
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False,
                                  label="Описание:")
    is_draft = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False,
                                  label="Черновик:")
    response_is_file = forms.BooleanField(widget=forms.CheckboxInput(attrs={"class": "form-check-input"}, ), required=False,
                                     label="Ответ в виде файла:")
    text = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}, ), required=False,
                                  label="Текст задания:")

    class Meta:
        model = Task
        fields = ['name', 'description', 'text', 'response_is_file', 'is_draft']


class UserForm(ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True)
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True)
    patronymic = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=False)
    is_staff = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'patronymic', 'email', 'is_staff', 'is_superuser']


class UserFormReadonly(ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True, disabled=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True, disabled=True)
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True, disabled=True)
    patronymic = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}, ), required=True, disabled=True)
    is_staff = forms.BooleanField(widget=forms.BooleanField(), disabled=True, required=False)
    is_superuser = forms.BooleanField(widget=forms.BooleanField(), disabled=True, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'patronymic', 'email', 'is_staff', 'is_superuser']

users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .functions import normalize_email


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'users/signupuser.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(password=request.POST['password1'],
                                                email=normalize_email(request.POST['email']),
                                                last_name=request.POST.get('last_name'),
                                                first_name=request.POST.get('first_name'),
                                                patronymic=request.POST.get('patronymic'))
                user.save()
                login(request, user)
                return redirect('home')

            except IntegrityError:
                return render(request, 'users/signupuser.html',
                              {'error': 'Электронный адрес уже используется'})
        else:
            return render(request, 'users/signupuser.html', {'error': 'Пароли не совпадают'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'users/loginuser.html')
    else:
        user = authenticate(request, email=request.POST['email'], password=request.POST['password'])
        if user is None:
            return render(request, 'users/loginuser.html',
                          {'form': AuthenticationForm(), 'error': 'Логин или пароль введены не верно'})
        else:
            login(request, user)
            return redirect('home')


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')
# Create your views here.

custom_admin/templates/custom_admin/add_lesson_test.html
{% extends 'custom_admin/base_admin.html' %}
{% block head %}
    {% load static %}
    <script src="/static/custom_admin/add_lesson_test.js"></script>
    <script src="/static/custom_admin/jquery-3.6.0.min.js"></script>

{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}

   <p>
        <label for="id_name">Название:</label>
        <br>
        <input class="w-50" type="text" name="name" maxlength="100" required="" id="id_name" value="{{ lesson.name }}">
    </p>

    <p>
        <label for="id_description">Описание:</label>
        <br>
        <textarea class="w-50" name="description" cols="40" rows="5" maxlength="1000" required="" id="id_description">{{ lesson.description }}</textarea>
    </p>

    <p>
        <label for="id_time">Время:</label>
        <br>
        <input type="number" name="time" value="15" required="" id="id_time" >
    </p>

    <p>
        <label for="id_min_ball">Минимальный балл:</label>
        <br>
        <input type="number" name="min_ball" value="60" required="" id="id_min_ball" >
    </p>

    <p>
        <label for="id_is_draft">Черновик:</label>
        <input type="checkbox" name="is_draft" id="id_is_draft">
    </p>

    <div id="questions">

        <input type="hidden" name="total_questions" value="1" id="total_questions">

        <fieldset id="q_1">
            <p>
                <label for="id_text_q_1">Вопрос:</label>
                <br>
                <input class="w-50" type="text" name="text_q_1" maxlength="100" required="" id="id_text_q_1">
                <a onclick="remove_question('q_1')"> <img src="/static/admin/img/icon-deletelink.svg" alt="False" title="Удплить вопрос"> </a>
            </p>

            <p>
                <label for="id_description_q_1">Примечание:</label>
                <br>
                <textarea class="w-50" name="description_q_1" cols="40" rows="3" maxlength="250" id="id_description_q_1"></textarea>
            </p>

            <div id="q_1_answers">

                <input type="hidden" name="total_answers_q_1" value="1" id="total_answers_q_1">

                <p id="q_1_a_1">
                    <input id="cb_1_q_1" type="checkbox" name="cb_1_q_1">
                    <input class="w-25" type="text" value="Вариант ответа" name="answer_1_q_1" maxlength="100" required="" id="answer_1_q_1">

                    <a onclick="remove_answer('q_1_a_1')">
                        <img src="/static/admin/img/icon-deletelink.svg" alt="False" title="Удплить вопрос">
                    </a>
                </p>

            </div>

            <a onclick="add_answer('q_1')"><img src="/static/admin/img/icon-addlink.svg" alt="False" title="Добавить ответ">  Добавить ответ</a>
            <br>
            <a onclick="add_question('q_1')"><img src="/static/admin/img/icon-addlink.svg" alt="False" title="Добавить вопрос">  Добавить вопрос</a>

        </fieldset>
    </div>
    <button type="submit" > Создать  </button>
</form>
{% endblock %}

custom_admin/templates/custom_admin/details_course.html
{% extends 'custom_admin/base_admin.html' %}

{% block content %}
<div class="row p-3">
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
    <li><a href="{% url 'custom_admin:general_page' %}" class="text-decoration-none text-reset"><h6>Главная > </h6></a></li>
    <li><a href="{% url 'custom_admin:all_courses' %}" class="text-decoration-none text-reset"><h6>Курсы > </h6></a></li>
            <li><a href="{% url 'custom_admin:details_course' course.id %}" class="text-decoration-none text-reset"><h6>{{ course.name }} > </h6></a></li>

    </ul>
</div>
<div class="p-3">
<form method="post" enctype="multipart/form-data" novalidate >
    {% csrf_token %}
    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название курса:</label>
    {{ form.name }}
    <label class="small mb-1" for="{{ form.photo.id_for_label }}">Фотография:</label>
    <br>
    {{ form.photo }}
    <br>
    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание курса:</label>
    {{ form.description }}
    <label class="small mb-1" for="{{ form.is_draft.id_for_label }}">Черновик:</label>
    {{ form.is_draft }}
    <div class="p-3">
    {% for module in modules %}
        <a href="{% url 'custom_admin:details_module' course.id module.id %}" class="text-decoration-none text-reset"><h2>{{ module.name }}</h2></a>
    {% endfor %}
    </div>
    <a href="{% url 'custom_admin:add_module' course.id %}" class="btn btn-primary">Добавить модуль</a>
    <input type="submit" value="Сохранить" class="btn btn-outline-primary">
</form>
</div>
{% endblock %}

custom_admin/templates/custom_admin/details_lesson_test.html
{% extends 'custom_admin/base_admin.html' %}
{% block head %}
    {% load static %}
    <script src="/static/custom_admin/add_lesson_test.js"></script>
    <script src="/static/custom_admin/jquery-3.6.0.min.js"></script>

{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}

    <p>
        <label for="id_name">Название:</label>
        <br>
        <input class="w-50" type="text" name="name" maxlength="100" required="" id="id_name" value="{{ lesson.name }}">
    </p>

    <p>
        <label for="id_description">Описание:</label>
        <br>
        <textarea name="description" class="w-50" cols="40" rows="10" maxlength="1000" required="" id="id_description">{{ lesson.description }}</textarea>
    </p>

    <p>
        <label for="id_time">Время:</label>
        <br>
        <input type="number" name="time" value="{{ lesson.time }}" required="" id="id_time" >
    </p>

    <p>
        <label for="id_min_ball">Минимальный балл:</label>
        <br>
        <input type="number" name="min_ball" value="{{ lesson.min_ball }}" required="" id="id_min_ball" >
    </p>



    <p>
        <label for="id_is_draft">Черновик:</label>
        <input type="checkbox" name="is_draft" id="id_is_draft" {% if lesson.is_draft %} checked="true" {% endif %}>
    </p>


    <div id="questions" class="w-100">

        <input type="hidden" name="total_questions" value="1" id="total_questions">

        {% for question in questions %}
        <fieldset id="added_q_{{ question.id }}">
            <p>
                <label for="id_added_text_q_{{ question.id }}">Вопрос:</label>
                <br>
                <input type="text" class="w-50" name="added_text_q_{{ question.id }}" maxlength="100" required="" id="id_added_text_q_{{ question.id }}" value="{{ question.text }}">
                <a onclick="delete_an_existing_q('added_q_{{ question.id }}', {{ question.id }})"><img src="/static/admin/img/icon-deletelink.svg" alt="False" title="Удплить вопрос"></a>
            </p>

            <p>
                <label for="id_added_description_q_{{ question.id }}">Примечание:</label>
                <br>
                <textarea class="w-50"  name="added_description_q_{{ question.id }}" cols="40" rows="3" maxlength="250" id="id_added_description_q_{{ question.id }}">{{ question.description }}</textarea>
            </p>

            <div id="added_q_{{ question.id }}_answers">

                <input  type="hidden" name="total_added_answers_q_{{ question.id }}" value="1" id="total_added_answers_q_{{ question.id }}">
                {% for answer in answers|get_item:question.id %}

                <p id="added_q_{{ question.id }}_a_{{ answer.id }}">
                    <input type="checkbox"  id="added_cb_{{ answer.id }}_q_{{ question.id }}" {% if answer.is_true %} checked="true" {% endif %} name="added_cb_{{ answer.id }}_q_{{ question.id }}">  <input class="w-25"  type="text" value="{{ answer.text }}" name="added_answer_{{ answer.id }}_q_{{ question.id }}" maxlength="100" required="" id="added_answer_{{ answer.id }}_q_{{ question.id }}"><a onclick="delete_an_existing_a('added_q_{{ question.id }}_a_{{ answer.id }}',{{ answer.id }})"> <img src="/static/admin/img/icon-deletelink.svg" alt="False" title="Удплить ответ"> </a>
                </p>

                {% endfor %}

            </div>

            <a onclick="add_answer_in_added('{{ question.id }}')"><img src="/static/admin/img/icon-addlink.svg" alt="False" title="Добавить ответ">  Добавить ответ</a>
            <br>
            <a onclick="add_question('added_q_{{ question.id }}')"><img src="/static/admin/img/icon-addlink.svg" alt="False" title="Добавить вопрос">  Добавить вопрос</a>

        </fieldset>
        {% endfor %}
    </div>
    <br>
    <button class="btn btn-primary" type="submit" name="save_and_quit" > Сохранить и выйти  </button> <button name="save" type="submit" class="btn btn-outline-primary" > Сохранить </button>
</form>
{% endblock %}

custom_admin/templates/custom_admin/details_module.html
{% extends 'custom_admin/base_admin.html' %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row p-3">
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
    <li><a href="{% url 'custom_admin:general_page' %}" class="text-decoration-none text-reset"><h6>Главная > </h6></a></li>
    <li><a href="{% url 'custom_admin:all_courses' %}" class="text-decoration-none text-reset"><h6>Курсы > </h6></a></li>
    <li><a href="{% url 'custom_admin:details_course' course.id %}" class="text-decoration-none text-reset"><h6>{{ course.name }} > </h6></a></li>
         <li><a href="{% url 'custom_admin:details_module' course.id module.id %}" class="text-decoration-none text-reset"><h6>{{ module.name }} > </h6></a></li>

    </ul>
</div>


<form method="post">
    {% csrf_token %}
    {% csrf_token %}
    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название модуля:</label>
    {{ form.name }}
    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание модуля:</label>
    {{ form.description }}
    <label class="small mb-1" for="{{ form.is_draft.id_for_label }}">Черновик:</label>
    {{ form.is_draft }}

 <h3>Уроки:</h3>
<div class="ps-3 pb-3">

{% for lesson in lessons %}
    <a href="{% url 'custom_admin:details_lesson' module.course_id.id module.id lesson.content_type lesson.id %}" class="text-decoration-none text-reset"><h3>{{ lesson.name }}</h3></a>
{% endfor %}
</div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Создать урок
</button>
<input type="submit" value="Сохранить" class="btn btn-outline-primary">
</form>





<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Создать урок</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body mx-auto">

          <a href="{% url 'custom_admin:add_lesson' module.course_id.id module.id 'vd' %}" class="btn btn-primary btn-sm">Видео</a>

          <a href="{% url 'custom_admin:add_lesson' module.course_id.id module.id 'lc' %}" class="btn btn-primary btn-sm">Лекция</a>

          <a href="{% url 'custom_admin:add_lesson' module.course_id.id module.id 'tk' %}" class="btn btn-primary btn-sm">Задание</a>

          <a href="{% url 'custom_admin:add_lesson' module.course_id.id module.id 'ts' %}" class="btn btn-primary btn-sm">Тест</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}